sudo: required
dist: trusty

language: node_js
node_js:
- '0.10'
before_install: npm install -g protractor@1.0.0 mocha@1.18.2
install:
- npm install
- webdriver-manager update --standalone

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'  

- sudo apt-get update -q
- sudo apt-get install -q google-chrome-stable
- webdriver-manager start &
script:
- npm run test-single-run
- npm install webdriverio
- (npm start > /dev/null &)  && (npm run protractor)
